---
  - name: Create directories
    file:
      path: /root/docker/socksproxy
      state: directory

  - name: Copy sockd conf
    template:
      src: templates/sockd.conf.j2
      dest: /root/docker/socksproxy/sockd.conf
    tags: update
