FROM {{ socks5_proxy_image }}

{% if socks5_proxy_auth == true %}
RUN {% for user in socks5_proxy_users %}printf '{{ user.password }}\n{{ user.password }}\n' | adduser {{ user.login }};{% endfor %}
{% endif %}
